Repository OZ-Coding-School/oz_02_main-003-FE, pull requests merged in 2024-06, with the labels that each got.

#24 style: loginpage ui 완성
  package-lock.json
  package.json
  src/assets/icons/bi.png
  src/assets/icons/google.png
  src/assets/icons/kakao.png
  src/assets/images/sample.png
  src/pages/LoginPage/components/LoginButtons.tsx
  src/pages/LoginPage/page/index.tsx
  src/pages/MainPage/components/Modal.tsx
Labels: 👨🏻‍🍳 김효중, STYLE

#28 Style: bookmarkPage 레이아웃 작업 완료
  src/pages/BookMarkPage/page/index.tsx
Labels: 👨🏻‍🍳 정재호, STYLE

#31 Style: RecipePage 레이아웃 작업완료
  src/assets/images/김치볶음밥.png
  src/components/badge/Badge.tsx
  src/components/buttons/BigButton.tsx
  src/components/buttons/MoreButton.tsx
  src/components/header/RecipeHeader.tsx
  src/components/modal/ProceedModal.tsx
  src/components/recipe/RecipeItem.tsx
  src/pages/RecipePage/components/DividingLine.tsx
  src/pages/RecipePage/components/comment/CommentIcon.tsx
  src/pages/RecipePage/components/comment/CommentItem.tsx
  src/pages/RecipePage/components/comment/CommentSection.tsx
  src/pages/RecipePage/components/ingredient/PreparedIngredients.tsx
  src/pages/RecipePage/components/step/RecipeSteps.tsx
  src/pages/RecipePage/components/stroy/RecipeStory.tsx
  src/pages/RecipePage/components/title/BadgeTitle.tsx
  src/pages/RecipePage/components/title/RecipeTitleSection.tsx
  src/pages/RecipePage/page/index.tsx
  src/types/recipeType.ts
Labels: 👩🏻‍🍳 최은진, STYLE

#34 Fix: 이미지 경로 오류 수정
  src/assets/images/cookImage.jpg
  src/components/footer/Footer.tsx
  src/components/header/ButtonHeader.tsx
  src/pages/RecipePage/page/index.tsx
  src/pages/RecipeRegistrationPage/components/Label.tsx
  src/pages/RecipeRegistrationPage/components/step/FirstStep.tsx
  src/pages/RecipeRegistrationPage/components/step/FourthStep.tsx
  src/pages/RecipeRegistrationPage/components/step/SecondStep.tsx
  src/pages/RecipeRegistrationPage/components/step/ThirdStep.tsx
  src/pages/RecipeRegistrationPage/page/index.tsx
Labels: 🛠️ FIX, 🚨 HOTFIX, 👩🏻‍🍳 최은진

#35 Fix: 기본 프로필 이미지 추가
  src/assets/images/basicProfile.jpg
  src/pages/RecipePage/page/index.tsx
Labels: 🛠️ FIX, 🚨 HOTFIX

#36 Style: 프로필 페이지 레이아웃 작업 완료
  src/App.tsx
  src/components/buttons/BigButton.tsx
  src/components/footer/Footer.tsx
  src/components/header/MainHeader.tsx
  src/pages/MainPage/components/BestRecipeItem.tsx
  src/pages/MainPage/components/CategorySection.tsx
  src/pages/MainPage/components/MainRecipeItem.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/ProfilePage/components/PostsList.tsx
  src/pages/ProfilePage/components/ProfileSection.tsx
  src/pages/ProfilePage/data/dummyData.ts
  src/pages/ProfilePage/page/index.tsx
  src/pages/RecipePage/components/comment/CommentItem.tsx
Labels: 👨🏻‍🍳 정재호, STYLE

#38 Style: 알림페이지 레이아웃 작업 완료
  src/pages/NotificationPage/components/NotificationItem.tsx
  src/pages/NotificationPage/page/index.tsx
  src/types/notificationItemType.ts
Labels: 👨🏻‍🍳 김효중, STYLE

#40 Fix: SelectBox,Header 컴포넌트 수정
  src/components/badge/StepBadge.tsx
  src/components/buttons/RectangularSmallButton.tsx
  src/components/filtering/FilteringButtons.tsx
  src/components/footer/Footer.tsx
  src/components/header/AccountHeader.tsx
  src/components/header/ButtonHeader.tsx
  src/components/header/Header.tsx
  src/components/header/MainHeader.tsx
  src/components/header/RecipeHeader.tsx
  src/components/header/SearchHeader.tsx
  src/components/modal/ProceedModal.tsx
  src/components/recipe/Like.tsx
  src/pages/RecipePage/components/step/RecipeSteps.tsx
  src/pages/RecipeRegistrationPage/components/imageUpload/ImageUpload.tsx
  src/pages/RecipeRegistrationPage/components/input/Input.tsx
  src/pages/RecipeRegistrationPage/components/selectbox/SelectBox.tsx
  src/pages/RecipeRegistrationPage/components/step/FirstStep.tsx
  src/pages/RecipeRegistrationPage/components/step/SecondStep.tsx
  src/pages/RecipeRegistrationPage/components/step/ThirdStep.tsx
  src/pages/RecipeRegistrationPage/page/index.tsx
  src/pages/SearchPage/page/index.tsx
  src/types/recipeType.ts
Labels: 🛠️ FIX, 🚨 HOTFIX, 👩🏻‍🍳 최은진

#42 Style: 메인 페이지 레이아웃 작업 완료
  package-lock.json
  package.json
  src/components/modal/ProceedModal.tsx
  src/components/recipe/RecipeItem.tsx
  src/pages/MainPage/components/BestRecipeItem.tsx
  src/pages/MainPage/components/BestRecipeList.tsx
  src/pages/MainPage/components/CategorySection.tsx
  src/pages/MainPage/components/CategorySectionItem.tsx
  src/pages/MainPage/components/CategorySectionList.tsx
  src/pages/MainPage/data/mainPageData.ts
  src/pages/MainPage/page/index.tsx
  src/pages/ProfilePage/components/PostsList.tsx
  src/pages/ProfilePage/components/ProfileSection.tsx
  src/pages/ProfilePage/data/dummyData.ts
  src/pages/ProfilePage/page/index.tsx
  src/pages/RecipePage/page/index.tsx
  src/types/mainPageDataType.ts
Labels: 🐛 BUG, 🛠️ FIX, 👨🏻‍🍳 정재호, STYLE

#44 Style: RecipeRegistrationPage 레이아웃 작업 완료
  package-lock.json
  package.json
  src/components/buttons/RectangularSmallButton.tsx
  src/components/header/ButtonHeader.tsx
  src/pages/RecipeRegistrationPage/components/Label.tsx
  src/pages/RecipeRegistrationPage/components/imageUpload/ImageUpload.tsx
  src/pages/RecipeRegistrationPage/components/ingredientbox/IngredientBox.tsx
  src/pages/RecipeRegistrationPage/components/input/IngredientInput.tsx
  src/pages/RecipeRegistrationPage/components/input/Input.tsx
  src/pages/RecipeRegistrationPage/components/input/TitleInput.tsx
  src/pages/RecipeRegistrationPage/components/selectbox/SelectBox.tsx
  src/pages/RecipeRegistrationPage/components/step/FirstStep.tsx
  src/pages/RecipeRegistrationPage/components/step/FourthStep.tsx
  src/pages/RecipeRegistrationPage/components/step/SecondStep.tsx
  src/pages/RecipeRegistrationPage/components/step/ThirdStep.tsx
  src/pages/RecipeRegistrationPage/page/index.tsx
  src/store/useRecipeStore.ts
  tsconfig.json
  vite.config.ts
Labels: 👩🏻‍🍳 최은진, STYLE

#48 Chore : api 경로 변수화 작업
  src/api/apiRoutes.ts
  src/pages/MainPage/components/CategorySectionList.tsx
  src/store/useRecipeStore.ts
Labels: ⚙️ CHORE, 👨🏻‍🍳 정재호

#43 Style: 냉장고 페이지 레이아웃 작업 완료
  src/components/recipe/Like.tsx
  src/components/recipe/Scrap.tsx
  src/pages/RefrigeratorPage/components/RefrigeratorItem.tsx
  src/pages/RefrigeratorPage/page/index.tsx
  src/types/refrigeratorType.ts
Labels: 👨🏻‍🍳 김효중, STYLE

#51 Deploy: 배포를 위한 코드 에러 잡기 작업
  package-lock.json
  package.json
  src/components/header/ButtonHeader.tsx
  src/components/recipe/RecipeItem.tsx
  src/pages/IngredientSelectionPage/page/index.tsx
  src/pages/IngredientsListPage/page/index.tsx
  src/pages/MainPage/components/BestRecipeItem.tsx
  src/pages/MainPage/components/CategorySectionItem.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/NotificationPage/components/NotificationItem.tsx
  src/pages/NotificationPage/page/index.tsx
  src/pages/RecipeListPage/page/index.tsx
  src/pages/RecipePage/page/index.tsx
  src/pages/RecipeRegistrationPage/components/step/FirstStep.tsx
  src/pages/RecipeRegistrationPage/components/step/SecondStep.tsx
  src/pages/RecipeRegistrationPage/components/step/ThirdStep.tsx
  src/pages/RecipeRegistrationPage/page/index.tsx
  src/pages/RecommendedRecipePage/page/index.tsx
  src/pages/RefrigeratorPage/components/RefrigeratorItem.tsx
  src/pages/RefrigeratorPage/page/index.tsx
  src/types/refrigeratorType.ts
  tailwind.config.js
Labels: 🛠️ FIX, 👨🏻‍🍳 정재호, DEPLOY

#52 Style:RecipeList 페이지 레이아웃 완료
  src/App.tsx
  src/pages/MainPage/components/BestRecipeList.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/RecipeListPage/page/index.tsx
  src/utils/ScrollTo.ts
Labels: 👩🏻‍🍳 최은진, STYLE

#53 Deploy: 배포를 위한 머지작업
  package-lock.json
  package.json
  src/App.tsx
  src/api/apiRoutes.ts
  src/components/header/ButtonHeader.tsx
  src/components/recipe/Like.tsx
  src/components/recipe/RecipeItem.tsx
  src/components/recipe/Scrap.tsx
  src/pages/IngredientSelectionPage/page/index.tsx
  src/pages/IngredientsListPage/page/index.tsx
  src/pages/MainPage/components/BestRecipeItem.tsx
  src/pages/MainPage/components/BestRecipeList.tsx
  src/pages/MainPage/components/CategorySectionItem.tsx
  src/pages/MainPage/components/CategorySectionList.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/NotificationPage/components/NotificationItem.tsx
  src/pages/NotificationPage/page/index.tsx
  src/pages/RecipeListPage/page/index.tsx
  src/pages/RecipePage/page/index.tsx
  src/pages/RecipeRegistrationPage/components/step/FirstStep.tsx
  src/pages/RecipeRegistrationPage/components/step/SecondStep.tsx
  src/pages/RecipeRegistrationPage/components/step/ThirdStep.tsx
  src/pages/RecipeRegistrationPage/page/index.tsx
  src/pages/RecommendedRecipePage/page/index.tsx
  src/pages/RefrigeratorPage/components/RefrigeratorItem.tsx
  src/pages/RefrigeratorPage/page/index.tsx
  src/store/useRecipeStore.ts
  src/types/refrigeratorType.ts
  src/utils/ScrollTo.ts
  tailwind.config.js
Labels: 👨🏻‍🍳 정재호, DEPLOY

#55 Fix: mainPage 데이터 형식 수정 및 모달 유효성 검사 추가 및 코드 수정
  src/pages/MainPage/components/BestRecipeItem.tsx
  src/pages/MainPage/components/CategorySectionItem.tsx
  src/pages/MainPage/components/Modal.tsx
  src/pages/MainPage/data/mainPageData.ts
  src/pages/MainPage/page/index.tsx
  src/types/mainPageDataType.ts
Labels: 🛠️ FIX, 👨🏻‍🍳 정재호

#56 Style: RecommededList page 레이아웃 작업 완료
  src/components/dividingLine/DividingLine.tsx
  src/pages/RecipePage/page/index.tsx
  src/pages/RecommendedRecipePage/components/RecommendedRecipeItem.tsx
  src/pages/RecommendedRecipePage/page/index.tsx
  src/types/recommededType.ts
Labels: 👩🏻‍🍳 최은진, STYLE

#57 Deploy: 배포를 위한 3차 merge
  src/components/dividingLine/DividingLine.tsx
  src/pages/MainPage/components/BestRecipeItem.tsx
  src/pages/MainPage/components/CategorySectionItem.tsx
  src/pages/MainPage/components/Modal.tsx
  src/pages/MainPage/data/mainPageData.ts
  src/pages/MainPage/page/index.tsx
  src/pages/RecipePage/page/index.tsx
  src/pages/RecommendedRecipePage/components/RecommendedRecipeItem.tsx
  src/pages/RecommendedRecipePage/page/index.tsx
  src/types/mainPageDataType.ts
  src/types/recommededType.ts
Labels: 👩🏻‍🍳 최은진, DEPLOY

#58 Conf: vercel.json에 rewrites 추가
  vercel.json
Labels: ⚙️ CHORE, 👨🏻‍🍳 정재호

#59 Deploy: 배포
  vercel.json
Labels: 👨🏻‍🍳 정재호, DEPLOY

#60 Style: 재료 선택 페이지 UI 작업 완료
  .prettierignore
  src/pages/IngredientSelectionPage/components/IngredientSelectionItem.tsx
  src/pages/IngredientSelectionPage/page/index.tsx
  src/pages/RefrigeratorPage/components/RefrigeratorItem.tsx
  src/pages/RefrigeratorPage/page/index.tsx
Labels: 👨🏻‍🍳 김효중, STYLE

#63 Conf: customAxios(메소드별 함수 작성) 및 최상위 컴포넌트에 queryclientprovider 걸어둠
  package-lock.json
  package.json
  src/api/axios.ts
  src/layout/Layout.css
  src/layout/Layout.tsx
  src/main.tsx
  src/pages/BookMarkPage/page/index.tsx
  src/pages/MainPage/components/Modal.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/ProfilePage/components/ProfileSection.tsx
  src/pages/ProfilePage/page/index.tsx
  tailwind.config.js
Labels: 🐛 BUG, 🛠️ FIX, ⚙️ CHORE, 👨🏻‍🍳 정재호, STYLE

#65 Chore: 배포에 필요한 작업
  index.html
  package-lock.json
  package.json
  src/assets/favicons/favicon-16x16.png
  src/assets/favicons/favicon-32x32.png
  src/assets/favicons/favicon-96x96.png
  src/assets/favicons/favicon.ico
  src/main.tsx
Labels: ⚙️ CHORE, 👨🏻‍🍳 정재호, DEPLOY

#66 Feat: 로그인 페이지 api 연결 작업 완료
  index.html
  src/api/apiRoutes.ts
  src/api/axios.ts
  src/pages/LoginPage/page/index.tsx
  vite.config.ts
Labels: 🚀 FEAT, 👨🏻‍🍳 정재호

#69 Feat: mainPage 기능 일부 구현(데이터가 없으므로 일단 더미데이터로 진행)
  package-lock.json
  package.json
  src/api/apiRoutes.ts
  src/pages/LoginPage/page/index.tsx
  src/pages/MainPage/page/index.tsx
  src/types/mainPageDataType.ts
Labels: 🚀 FEAT, 🛠️ FIX, 👨🏻‍🍳 정재호, DEPLOY

#70 Deploy: 메인페이지와 로그인페이지 기능 구현 후 배포 최신화
  .prettierignore
  index.html
  package-lock.json
  package.json
  src/api/apiRoutes.ts
  src/api/axios.ts
  src/assets/favicons/favicon-16x16.png
  src/assets/favicons/favicon-32x32.png
  src/assets/favicons/favicon-96x96.png
  src/assets/favicons/favicon.ico
  src/layout/Layout.css
  src/layout/Layout.tsx
  src/main.tsx
  src/pages/BookMarkPage/page/index.tsx
  src/pages/IngredientSelectionPage/components/IngredientSelectionItem.tsx
  src/pages/IngredientSelectionPage/page/index.tsx
  src/pages/IngredientsListPage/components/IngredientsListItem.tsx
  src/pages/IngredientsListPage/components/Search.tsx
  src/pages/IngredientsListPage/page/index.tsx
  src/pages/LoginPage/page/index.tsx
  src/pages/MainPage/components/Modal.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/ProfilePage/components/ProfileSection.tsx
  src/pages/ProfilePage/page/index.tsx
  src/pages/RefrigeratorPage/components/RefrigeratorItem.tsx
  src/pages/RefrigeratorPage/page/index.tsx
  src/types/ingredientType.ts
  src/types/mainPageDataType.ts
  tailwind.config.js
  vite.config.ts
Labels: 🚀 FEAT, 👨🏻‍🍳 정재호, DEPLOY

#73 Feat: mainPage skeleton loading 수정
  src/pages/MainPage/components/MainRecipeItem.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/MainPage/skeleton/SkeletonImageLoader.tsx
  src/pages/MainPage/skeleton/SkeletonLoader.tsx
Labels: 🚀 FEAT, 🛠️ FIX, 👨🏻‍🍳 정재호

#75 Feature: Setting Page api 연동 작업 완료
  src/api/apiRoutes.ts
  src/components/recipe/RecipeItem.tsx
  src/components/recipe/RecipeList.tsx
  src/pages/ErrorPage/index.tsx
  src/pages/IngredientSelectionPage/components/IngredientSelectionItem.tsx
  src/pages/IngredientSelectionPage/page/index.tsx
  src/pages/IngredientsListPage/components/IngredientsListItem.tsx
  src/pages/IngredientsListPage/page/index.tsx
  src/pages/LoginPage/page/index.tsx
  src/pages/MainPage/components/BestRecipeItem.tsx
  src/pages/MainPage/components/BestRecipeList.tsx
  src/pages/MainPage/components/CategorySectionItem.tsx
  src/pages/MainPage/components/CategorySectionList.tsx
  src/pages/MainPage/data/mainPageData.ts
  src/pages/MainPage/page/index.tsx
  src/pages/NotificationPage/components/NotificationItem.tsx
  src/pages/NotificationPage/page/index.tsx
  src/pages/ProfilePage/components/PostsList.tsx
  src/pages/ProfilePage/data/dummyData.ts
  src/pages/RefrigeratorPage/components/RefrigeratorItem.tsx
  src/pages/RefrigeratorPage/page/index.tsx
  src/pages/SearchPage/page/index.tsx
  src/pages/SettingPage/page/index.tsx
  src/types/accountRecipeType.ts
  src/types/alertType.ts
  src/types/ingredientType.ts
  src/types/mainPageDataType.ts
  src/types/notificationItemType.ts
  src/types/recipeItemType.ts
  src/types/refrigeratorType.ts
  vite.config.ts
Labels: 🚀 FEAT, 👨🏻‍🍳 정재호

#80 Feature: 좋아요 페이지, 북마크 페이지 api 연동작업 완료
  src/components/recipe/RecipeItem.tsx
  src/components/recipe/SkeletonRecipeList.tsx
  src/pages/BookMarkPage/page/index.tsx
  src/pages/LikedPage/page/index.tsx
  src/types/recipeItemType.ts
Labels: 🚀 FEAT, 🛠️ FIX, 👨🏻‍🍳 정재호

#81 Feature: RecipeRegistration 페이지 api 연동작업 완료
  src/api/apiRoutes.ts
  src/components/header/RecipeHeader.tsx
  src/pages/RecipePage/page/index.tsx
  src/pages/RecipeRegistrationPage/components/imageUpload/MainImageUpload.tsx
  src/pages/RecipeRegistrationPage/components/imageUpload/StepImageUpload.tsx
  src/pages/RecipeRegistrationPage/components/ingredientbox/IngredientBox.tsx
  src/pages/RecipeRegistrationPage/components/selectbox/SelectBox.tsx
  src/pages/RecipeRegistrationPage/components/step/FirstStep.tsx
  src/pages/RecipeRegistrationPage/components/step/FourthStep.tsx
  src/pages/RecipeRegistrationPage/components/step/SecondStep.tsx
  src/pages/RecipeRegistrationPage/components/step/ThirdStep.tsx
  src/pages/RecipeRegistrationPage/page/index.tsx
  src/store/useImageStore.ts
  src/store/useRecipeStore.ts
  src/types/imageUploadType.ts
  src/types/recipeType.ts
  src/types/selectBoxType.ts
  src/utils/selectUnits.ts
Labels: 👩🏻‍🍳 최은진, STYLE

#82 Feat: mainPage api 연동해서 get 해오는 작업 완료
  src/pages/MainPage/components/BestBookmarkedRecipeItem.tsx
  src/pages/MainPage/components/BestRecipeItem.tsx
  src/pages/MainPage/components/BestRecipeList.tsx
  src/pages/MainPage/components/CategorySectionList.tsx
  src/pages/MainPage/data/mainPageData.ts
  src/pages/MainPage/page/index.tsx
  src/types/mainPageDataType.ts
Labels: 🚀 FEAT, 🛠️ FIX, 👨🏻‍🍳 정재호

#86 Fix: Like, Scrap 컴포넌트 Props 수정
  src/components/header/RecipeHeader.tsx
  src/components/recipe/Like.tsx
  src/components/recipe/RecipeItem.tsx
  src/components/recipe/RecipeList.tsx
  src/components/recipe/Scrap.tsx
  src/pages/BookMarkPage/page/index.tsx
  src/pages/LikedPage/page/index.tsx
  src/pages/MainPage/components/BestBookmarkedRecipeItem.tsx
  src/pages/MainPage/components/BestRecipeItem.tsx
  src/pages/MainPage/components/CategorySectionItem.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/RecipePage/components/comment/CommentSection.tsx
  src/pages/RecipePage/components/step/RecipeSteps.tsx
  src/pages/RecipePage/components/title/RecipeTitleSection.tsx
  src/pages/RecipePage/page/index.tsx
  src/pages/RecipeRegistrationPage/components/imageUpload/MainImageUpload.tsx
  src/pages/RecipeRegistrationPage/components/ingredientbox/IngredientBox.tsx
  src/pages/RecipeRegistrationPage/page/index.tsx
  src/pages/RecommendedRecipePage/components/RecommendedRecipeItem.tsx
  src/store/useImageStore.ts
  src/types/bookMarkType.ts
  src/types/likeType.ts
  src/types/recipeType.ts
Labels: 🛠️ FIX, 🚨 HOTFIX, 👩🏻‍🍳 최은진

#87 Feat: 레시피 목록 페이지 sort 구현 완료
  src/components/filtering/FilteringButtons.tsx
  src/components/recipe/Like.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/RecipeListPage/page/index.tsx
  src/pages/RecipeListPage/skeleton/SkeletonRecipeListLoader.tsx
Labels: 🚀 FEAT, 👨🏻‍🍳 김효중

#89 Feature: Profile 페이지 기능 구현 완료
  src/components/header/Bell.tsx
  src/components/header/Header.tsx
  src/components/header/MainHeader.tsx
  src/pages/MainPage/components/BestRecipeItem.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/ProfilePage/components/PostsList.tsx
  src/pages/ProfilePage/components/ProfileSection.tsx
  src/pages/ProfilePage/page/index.tsx
  src/pages/ProfilePage/skeleton/SkeletonPostsList.tsx
  src/pages/ProfilePage/skeleton/SkeletonProfileLoader.tsx
  src/pages/ProfilePage/skeleton/SkeletonProfileSection.tsx
  src/types/accountRecipeType.ts
  src/types/alertType.ts
Labels: 🚀 FEAT, 🛠️ FIX, 👨🏻‍🍳 정재호

#91 Feat: 알림페이지 기능 구현 완료
  src/api/axios.ts
  src/pages/NotificationPage/components/NotificationItem.tsx
  src/pages/NotificationPage/page/index.tsx
  src/types/notificationItemType.ts
Labels: 🚀 FEAT, ⚙️ CHORE, 👨🏻‍🍳 김효중, STYLE

#92 Feature: 레시피 페이지 기능 구현 완료
  package-lock.json
  package.json
  src/components/buttons/MoreButton.tsx
  src/components/header/RecipeHeader.tsx
  src/components/loading/Loading.tsx
  src/pages/RecipeListPage/page/index.tsx
  src/pages/RecipePage/components/comment/CommentItem.tsx
  src/pages/RecipePage/components/comment/CommentSection.tsx
  src/pages/RecipePage/components/step/RecipeSteps.tsx
  src/pages/RecipePage/components/title/RecipeTitleSection.tsx
  src/pages/RecipePage/page/index.tsx
  src/pages/RecipeRegistrationPage/components/imageUpload/StepImageUpload.tsx
  src/pages/RecipeRegistrationPage/components/ingredientbox/IngredientBox.tsx
  src/pages/RecipeRegistrationPage/components/step/SecondStep.tsx
  src/pages/RecipeRegistrationPage/page/index.tsx
Labels: 🚀 FEAT, 👩🏻‍🍳 최은진

#96 Feature: 검색페이지 구현 완료
  src/assets/images/basicProfile.jpg
  src/assets/images/cookImage.jpg
  src/assets/images/recipe.png
  src/assets/images/sample.png
  src/assets/images/김치볶음밥.png
  src/components/filtering/FilteringButtons.tsx
  src/components/header/SearchHeader.tsx
  src/pages/RecipeListPage/page/index.tsx
  src/pages/SearchPage/page/index.tsx
  src/types/recipeItemType.ts
Labels: 🚀 FEAT, 👩🏻‍🍳 최은진

#98 Feature: 냉장고 페이지 api 연동 작업 완료
  src/components/header/Bell.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/ProfilePage/page/index.tsx
  src/pages/RecipeListPage/page/index.tsx
  src/pages/RefrigeratorPage/components/RefrigeratorItem.tsx
  src/pages/RefrigeratorPage/page/index.tsx
  src/pages/RefrigeratorPage/skeleton/SkeletonRefrigeratorLoader.tsx
  src/pages/SettingPage/page/index.tsx
  src/types/alertType.ts
  src/types/ingredientType.ts
  src/types/refrigeratorType.ts
Labels: 🚀 FEAT, 👨🏻‍🍳 정재호

#99 Feature: Axios interceptor 설정 완료
  src/api/axios.ts
  src/pages/RecipePage/page/index.tsx
Labels: 🚀 FEAT, 👩🏻‍🍳 최은진

#103 Feature: 재료 선택 페이지 기능 구현 완료
  src/components/buttons/BigButton.tsx
  src/pages/IngredientSelectionPage/page/index.tsx
  src/pages/RefrigeratorPage/page/index.tsx
  src/types/recommededType.ts
Labels: 🚀 FEAT, 👩🏻‍🍳 최은진

#105 Feature: 추천 레시피 페이지 구현 완료
  src/components/recipe/Like.tsx
  src/components/recipe/Scrap.tsx
  src/pages/IngredientSelectionPage/page/index.tsx
  src/pages/IngredientsListPage/page/index.tsx
  src/pages/RecipeListPage/page/index.tsx
  src/pages/RecipeListPage/skeleton/SkeletonRecipeListLoader.tsx
  src/pages/RecipeRegistrationPage/components/step/SecondStep.tsx
  src/pages/RecommendedRecipePage/components/RecommendedRecipeItem.tsx
  src/pages/RecommendedRecipePage/page/index.tsx
  src/pages/RefrigeratorPage/page/index.tsx
  src/pages/SearchPage/page/index.tsx
  src/types/bookMarkType.ts
  src/types/likeType.ts
Labels: 🚀 FEAT, 👩🏻‍🍳 최은진

#106 Fix : 레시피 등록 페이지 기능 수정
  package-lock.json
  package.json
  src/App.tsx
  src/api/apiRoutes.ts
  src/api/axios.ts
  src/components/header/RecipeHeader.tsx
  src/pages/LoginPage/page/index.tsx
  src/pages/RecipeListPage/page/index.tsx
  src/pages/RecipePage/components/comment/CommentItem.tsx
  src/pages/RecipePage/components/comment/CommentSection.tsx
  src/pages/RecipePage/components/ingredient/PreparedIngredients.tsx
  src/pages/RecipePage/components/title/RecipeTitleSection.tsx
  src/pages/RecipePage/page/index.tsx
  src/pages/RecipeRegistrationPage/components/imageUpload/MainImageUpload.tsx
  src/pages/RecipeRegistrationPage/components/imageUpload/StepImageUpload.tsx
  src/pages/RecipeRegistrationPage/components/ingredientbox/IngredientBox.tsx
  src/pages/RecipeRegistrationPage/components/step/FirstStep.tsx
  src/pages/RecipeRegistrationPage/components/step/SecondStep.tsx
  src/pages/RecipeRegistrationPage/components/step/ThirdStep.tsx
  src/pages/RecipeRegistrationPage/page/index.tsx
  src/pages/RecommendedRecipePage/page/index.tsx
  src/store/useImageStore.ts
  src/store/useRecipeStore.ts
  src/types/recipeType.ts
Labels: 🚀 FEAT, 👩🏻‍🍳 최은진

#109 Fix: 세팅페이지 오류 해결
  src/pages/SettingPage/page/index.tsx
Labels: 🐛 BUG, 🛠️ FIX, 👨🏻‍🍳 정재호

#112 Fix: 재료 목록 페이지 오류 수정
  src/App.tsx
  src/pages/IngredientsListPage/components/IngredientsListItem.tsx
  src/pages/IngredientsListPage/page/index.tsx
  src/pages/NotificationPage/page/index.tsx
Labels: 🛠️ FIX, 👩🏻‍🍳 최은진

#113 Fix: 알림페이지 오류 수정
  src/pages/NotificationPage/components/NotificationItem.tsx
  src/pages/NotificationPage/page/index.tsx
  src/types/notificationItemType.ts
Labels: 🛠️ FIX, 👨🏻‍🍳 김효중

#114 Fix: 추천레시피 좋아요 스크랩버튼 눌렀을때 데이터 다시 받아오지 않아 최신화안하는 오류 해결
  src/components/recipe/Like.tsx
  src/pages/RecommendedRecipePage/components/RecommendedRecipeItem.tsx
  src/pages/RecommendedRecipePage/page/index.tsx
Labels: 🐛 BUG, 🚀 FEAT, 🛠️ FIX, 👨🏻‍🍳 정재호

#116 Fix/recommended/ej
  src/api/axios.ts
  src/pages/IngredientsListPage/components/IngredientsListItem.tsx
  src/pages/IngredientsListPage/page/index.tsx
  src/pages/RefrigeratorPage/page/index.tsx
  src/store/useIngredientStore.ts
Labels: 🛠️ FIX, 👩🏻‍🍳 최은진

#119 Feature: 레시피 페이지 공유하기, 다른 유저 프로필 이동 구현
  src/components/header/RecipeHeader.tsx
  src/pages/ProfilePage/components/ProfileSection.tsx
  src/pages/ProfilePage/data/dummyData.ts
  src/pages/ProfilePage/page/index.tsx
  src/pages/RecipePage/components/comment/CommentItem.tsx
  src/pages/RecipePage/components/title/RecipeTitleSection.tsx
  src/pages/RecipePage/page/index.tsx
Labels: 🚀 FEAT, 👩🏻‍🍳 최은진

#121 Fix: 다른 사람 프로필 페이지 오류 수정
  src/pages/ProfilePage/page/index.tsx
Labels: 🐛 BUG, 🚨 HOTFIX, 👨🏻‍🍳 정재호

#122 Deploy: 배포 최신화
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/pages/ProfilePage/page/index.tsx
  src/routes/CommonRoute.tsx
  src/routes/ProtectedRoute.tsx
Labels: 👨🏻‍🍳 정재호, DEPLOY

#123 Fix: 로그인 상태 여부에따른 리디렉션 걸어주는 부분 수정
  src/App.tsx
  src/routes/CommonRoute.tsx
  src/routes/ProtectedRoute.tsx
Labels: 🛠️ FIX, 👨🏻‍🍳 정재호

#124 Chore: 오류 수정한거 배포서버에서 확인하기 위한 push
  src/App.tsx
  src/pages/LoginPage/page/index.tsx
  src/routes/CommonRoute.tsx
  src/routes/ProtectedRoute.tsx
Labels: 🛠️ FIX, 👨🏻‍🍳 정재호, DEPLOY

#126 Fix: 배포서버에서 오류 수정한거 시도하기 위한 push
  src/App.tsx
  src/pages/MainPage/components/CategorySectionList.tsx
  src/pages/MainPage/page/index.tsx
  src/routes/CommonRoute.tsx
  src/routes/ProtectedRoute.tsx
Labels: 🐛 BUG, 🚀 FEAT, 👨🏻‍🍳 정재호

#131 Fix: 리디렉션 기능 수정
  src/App.tsx
  src/components/header/RecipeHeader.tsx
  src/components/header/SearchHeader.tsx
  src/pages/LoginPage/page/index.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/RecipePage/components/comment/CommentSection.tsx
  src/pages/RecipePage/components/step/RecipeSteps.tsx
  src/pages/RecipePage/page/index.tsx
  src/pages/RecipeRegistrationPage/components/imageUpload/MainImageUpload.tsx
  src/pages/SearchPage/page/index.tsx
  src/routes/ProtectedRoute.tsx
Labels: 🛠️ FIX, 🚨 HOTFIX, 👩🏻‍🍳 최은진

#132 Fix: 오류 수정
  src/App.tsx
  src/components/header/RecipeHeader.tsx
  src/components/header/SearchHeader.tsx
  src/pages/LoginPage/page/index.tsx
  src/pages/MainPage/page/index.tsx
  src/pages/RecipePage/components/comment/CommentSection.tsx
  src/pages/RecipePage/components/step/RecipeSteps.tsx
  src/pages/RecipePage/page/index.tsx
  src/pages/RecipeRegistrationPage/components/imageUpload/MainImageUpload.tsx
  src/pages/RecipeRegistrationPage/components/step/ThirdStep.tsx
  src/pages/RefrigeratorPage/page/index.tsx
  src/pages/SearchPage/page/index.tsx
  src/routes/ProtectedRoute.tsx
Labels: 🐛 BUG, 🚨 HOTFIX, 👨🏻‍🍳 정재호, DEPLOY

#144 Bug: 알림 페이지 스크랩 상태 처리 추가
  src/pages/NotificationPage/components/NotificationItem.tsx
  src/types/notificationItemType.ts
Labels: 🚀 FEAT, 👩🏻‍🍳 최은진
